#!/usr/bin/env python3
"""
h2_1_cgu16_all43.py — Phase 2 / hypothesis 2.1 (the most important item in
this study).

The codegen-units claim in bench/rulemine/REPORT.md / JOURNAL.md is a
crate-set confound: V3 (codegen-units axis) is 20 crates, main is 43, and
matched on crates the effect was measured at -1.03pp (preprint-v2.tex Table
knobs, "single pair" caveat) — pointing the OTHER way from an earlier "+7pp"
claim that pooled mismatched crate sets. This fixes it: rebuild ALL 43
crates at codegen-units=16 (holding lto=thin, opt-3, panic=unwind fixed,
same toolchain, same lockfiles -- via bench/rulemine/build_v3.sh, UNCHANGED,
just given all 43 crate names instead of 20), then recompute the ceiling and
R1/R2/R3/A@2 on the full matched set.

Prerequisite: bench/hypotheses/run_h2_1_build.sh must have completed (it
calls build_v3.sh unmodified for the 23 crates V3 didn't already have, then
regenerates bench/rulemine/v3/fde/*.parquet via build_dataset_aux.py --
gitignored derived data, not a tracked-tree modification, matching the
study's own convention: "regenerated by `make all`... none of it belongs in
git").

This script itself only reads bench/rulemine/data/fde (main, cgu=1) and
bench/rulemine/v3/fde (cgu=16/4, once regenerated); it does not build
anything.

Outputs: bench/hypotheses/h2_1_output.json, bench/hypotheses/h2_1_output.md
"""
import json
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
STUDY = os.path.join(ROOT, "bench", "rulemine")
sys.path.insert(0, os.path.join(STUDY, "lib"))
import mining  # noqa: E402
import protocol as P  # noqa: E402

R1 = "M_rel_structs >= 2 AND N_win_rel >= 3"
R2 = "M_rel_structs >= 2 AND X_caller_rel >= 1"
R3 = "M_rel_structs >= 1 AND N_win_rel >= 5"
A2 = "C_user >= 2 AND P_nonrel <= 0"
RULES = {"A@2": A2, "R1": R1, "R2": R2, "R3": R3}


def load_v3_config(cfg_suffix):
    d = os.path.join(STUDY, "v3", "fde")
    files = sorted(f for f in os.listdir(d) if f.endswith(f"{cfg_suffix}.parquet"))
    frames = []
    for f in files:
        crate = f.split("__", 1)[0]
        df = pd.read_parquet(os.path.join(d, f))
        df["crate"] = crate
        frames.append(df)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def load_main_config(cfg):
    d = os.path.join(STUDY, "data", "fde")
    files = sorted(f for f in os.listdir(d) if f.endswith(f"__{cfg}.parquet"))
    frames = [pd.read_parquet(os.path.join(d, f)) for f in files]
    return pd.concat(frames, ignore_index=True)


def ceiling_per_crate(df):
    y = P.target(df, "ws")
    has = (df["M_rel_structs"] >= 1).to_numpy()
    out = {}
    for crate, g in df.groupby("crate"):
        yy = P.target(g, "ws")
        hh = (g["M_rel_structs"] >= 1).to_numpy()
        if yy.sum() == 0:
            continue
        out[crate] = float((yy & hh).sum() / yy.sum())
    return out


def rule_scores(df, keep_labeled=True):
    d = df[~df["label"].isin(["NONE", "UNKNOWN"])].reset_index(drop=True) if keep_labeled else df
    y = P.target(d, "ws")
    out = {}
    for name, expr in RULES.items():
        pred = mining.eval_expr(d, expr)
        tp = int((y & pred).sum())
        pp = int(pred.sum())
        out[name] = {
            "precision": round(tp / pp, 4) if pp else None,
            "recall": round(tp / y.sum(), 4) if y.sum() else None,
            "fires": pp,
        }
    return out


def main():
    v3_dir = os.path.join(STUDY, "v3", "fde")
    if not (os.path.isdir(v3_dir) and os.listdir(v3_dir)):
        print("MISSING: bench/rulemine/v3/fde is empty -- run "
              "bench/hypotheses/run_h2_1_build.sh first (build + dataset regen).",
              file=sys.stderr)
        return 1

    cgu16 = load_v3_config("cgu-16_lto-thin_opt-3_panic-unwind")
    n_crates_cgu16 = cgu16["crate"].nunique()
    print(f"cgu=16/lto=thin builds available: {n_crates_cgu16} crates", file=sys.stderr)

    cgu1 = load_main_config("lto-thin_opt-3_panic-unwind")  # main corpus, cgu=1 (fixed study-wide)
    matched_crates = sorted(set(cgu16["crate"]) & set(cgu1["crate"]))
    print(f"matched crates (present in both cgu=1 and cgu=16, lto=thin): {len(matched_crates)}",
          file=sys.stderr)

    c16 = ceiling_per_crate(cgu16[cgu16["crate"].isin(matched_crates)])
    c1 = ceiling_per_crate(cgu1[cgu1["crate"].isin(matched_crates)])
    common = sorted(set(c16) & set(c1))
    deltas = [100 * (c16[c] - c1[c]) for c in common]

    out = {
        "header": {
            "n_crates_target": 43,
            "n_crates_cgu16_built": int(n_crates_cgu16),
            "n_crates_matched_for_ceiling": len(common),
        },
        "per_crate_ceiling_pct": {c: {"cgu1": round(100 * c1[c], 2), "cgu16": round(100 * c16[c], 2),
                                       "delta_pp": round(100 * (c16[c] - c1[c]), 2)} for c in common},
        "matched_ceiling_delta": {
            "mean_pp": round(float(np.mean(deltas)), 3) if deltas else None,
            "median_pp": round(float(np.median(deltas)), 3) if deltas else None,
            "n": len(deltas),
            "n_positive": int(sum(1 for d in deltas if d > 0)),
            "n_negative": int(sum(1 for d in deltas if d < 0)),
        },
    }

    pooled_cgu1 = ceiling_per_crate(cgu1[cgu1["crate"].isin(matched_crates)])  # unused, kept for clarity
    y1 = P.target(cgu1[cgu1["crate"].isin(matched_crates)], "ws")
    h1 = (cgu1[cgu1["crate"].isin(matched_crates)]["M_rel_structs"] >= 1).to_numpy()
    y16 = P.target(cgu16[cgu16["crate"].isin(matched_crates)], "ws")
    h16 = (cgu16[cgu16["crate"].isin(matched_crates)]["M_rel_structs"] >= 1).to_numpy()
    out["pooled_ceiling"] = {
        "cgu1_pct": round(100 * (y1 & h1).sum() / y1.sum(), 3),
        "cgu16_pct": round(100 * (y16 & h16).sum() / y16.sum(), 3),
        "pooled_delta_pp": round(100 * ((y16 & h16).sum() / y16.sum() - (y1 & h1).sum() / y1.sum()), 3),
    }

    out["rules_cgu1"] = rule_scores(cgu1[cgu1["crate"].isin(matched_crates)])
    out["rules_cgu16"] = rule_scores(cgu16[cgu16["crate"].isin(matched_crates)])
    out["neighbourhood_advantage"] = {}
    for r in ("R1", "R3"):
        a2_r1 = out["rules_cgu1"][r]["recall"] - out["rules_cgu1"]["A@2"]["recall"]
        a16_r1 = out["rules_cgu16"][r]["recall"] - out["rules_cgu16"]["A@2"]["recall"]
        out["neighbourhood_advantage"][r] = {
            "recall_advantage_cgu1_pp": round(100 * a2_r1, 2) if a2_r1 is not None else None,
            "recall_advantage_cgu16_pp": round(100 * a16_r1, 2) if a16_r1 is not None else None,
            "weakens_at_cgu16": bool(a16_r1 < a2_r1) if (a2_r1 is not None and a16_r1 is not None) else None,
        }

    with open(os.path.join(HERE, "h2_1_output.json"), "w") as fh:
        json.dump(out, fh, indent=2, default=float)

    lines = ["# h2.1 -- V3 (codegen-units=16) on all 43 crates", ""]
    lines.append(f"Crates with cgu=16/lto=thin built: {n_crates_cgu16}/43. "
                 f"Matched against main-corpus cgu=1/lto=thin: {len(common)} crates.")
    lines.append("")
    lines.append(f"**Matched per-crate ceiling delta (cgu=16 - cgu=1): mean "
                 f"{out['matched_ceiling_delta']['mean_pp']}pp, median "
                 f"{out['matched_ceiling_delta']['median_pp']}pp, n={out['matched_ceiling_delta']['n']} "
                 f"({out['matched_ceiling_delta']['n_positive']} positive / "
                 f"{out['matched_ceiling_delta']['n_negative']} negative)**")
    lines.append("")
    lines.append(f"Pooled ceiling: cgu=1 {out['pooled_ceiling']['cgu1_pct']}% -> "
                 f"cgu=16 {out['pooled_ceiling']['cgu16_pct']}% "
                 f"(delta {out['pooled_ceiling']['pooled_delta_pp']}pp)")
    lines.append("")
    lines.append("## Rules at cgu=1 vs cgu=16 (matched 43 -- as many as built)")
    lines.append("")
    lines.append("| rule | cgu1 prec/recall | cgu16 prec/recall |")
    lines.append("|---|---|---|")
    for r in RULES:
        a = out["rules_cgu1"][r]
        b = out["rules_cgu16"][r]
        lines.append(f"| {r} | {a['precision']}/{a['recall']} | {b['precision']}/{b['recall']} |")
    lines.append("")
    lines.append("## Does the neighbourhood advantage weaken as CGU coarsens?")
    lines.append("")
    for r, d in out["neighbourhood_advantage"].items():
        lines.append(f"- {r}: recall advantage over A@2 at cgu=1 = {d['recall_advantage_cgu1_pp']}pp, "
                     f"at cgu=16 = {d['recall_advantage_cgu16_pp']}pp -- "
                     f"{'WEAKENS' if d['weakens_at_cgu16'] else 'DOES NOT WEAKEN'}")

    with open(os.path.join(HERE, "h2_1_output.md"), "w") as fh:
        fh.write("\n".join(lines))
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
