#!/usr/bin/env bash
# wake_4am.sh — re-enter the measurement with a fresh Claude session after the token
# reset, and carry it to completion.
#
# This session cannot resume itself: a token/usage limit arrives as an error on a tool
# call, and a cut-off session cannot restart from a shell. So a NEW session is started
# instead. It gets no memory of the old one -- everything it needs is on disk:
#   RESULTS.md            the running write-up, incl. what is done and what is left
#   realval/*.py, *.sh    the committed harness
#   git log               decisions and why
#
# run_all.sh (the autonomous pipeline) should already have produced the numbers without
# any model in the loop. This session's job is the judgment work that a script cannot do:
# auditing every false attribution, and finishing the prose.
set -u

cd /home/user/Videos/unhusk || exit 1
LOG="realval/wake_4am.log"
{
  echo "=== wake_4am fired $(date -Is)"
  echo "--- pipeline state ---"
  ls -la realval/rows_*.json RESULTS.md 2>&1 | tail -5
  tail -3 realval/run_all.log 2>/dev/null
} >> "$LOG" 2>&1

PROMPT=$(cat <<'EOF'
You are resuming an overnight measurement run on the unhusk repo (/home/user/Videos/unhusk).
You have NO memory of the earlier session. Everything is on disk. Read these first, in order:

  1. RESULTS.md   -- the running write-up. Its "Still outstanding" section is your task list.
  2. git log --oneline -15   -- the decisions taken and why.
  3. realval/run_all.log     -- what the autonomous pipeline did while nobody was watching.

THE GOAL: lock unhusk's symbol-based attribution precision to a defensible number with a
confidence interval, split sync vs async. MEASUREMENT ONLY. Do NOT modify unhusk's
attribution logic (src/), do NOT touch winnow, do NOT redesign anything. If you want to
"improve" something, log it in RESULTS.md instead.

HARD RULES:
  - Fabricated or interpolated numbers are unacceptable. Every figure must come from a
    script over binaries on disk. "Stuck at step X" / "n too small to state a CI" is a
    CORRECT answer -- write it down, do not paper over it.
  - Wilson score intervals, not bare point estimates. The cluster bootstrap (resampling
    binaries) is the honest interval because functions cluster by binary; report both.
  - RESULTS.md must end with: n per stratum, point estimate, CI, and a FULL list of every
    false attribution (function + symbol + why) so it can be audited by hand.
  - Commit to main as you go. Do NOT push. Never put Co-Authored-By or session links in
    commit messages.

IMPORTANT — AS OF 01:05 THE MEASUREMENT IS ALREADY COMPLETE.
32/32 binaries passed the provenance gate; 2225 certain functions; every number, CI and
the full 67-row false-attribution list are already in RESULTS.md, generated by
realval/report_results.py from realval/rows_src.json. Every docs/local/validation.md headline
replicated (STRONG pooled 94.2% vs 94.4%; async 88.7% vs ~87.3%; ladder >=3 96.1% vs
96.1%). The working tree is clean and everything is committed.

So your job is NARROW. Do NOT re-run the pipeline. Do NOT rebuild the corpus. Do NOT
recompute numbers that already exist. Doing so risks churning a finished deliverable.

Do this instead, in order, and stop when done:
  1. Read RESULTS.md end to end. Sanity-check it for internal contradictions -- numbers in
     the TL;DR that disagree with the generated tables below the marker, or claims that
     the data does not support. Fix ONLY genuine inconsistencies, in RESULTS.md.
  2. Audit the generated false-attribution table below the marker. The `author-param?`
     column is what matters. Rows marked *undeterminable (legacy mangling)* CANNOT be
     classified from the symbol -- say so, never guess (RESULTS.md 5e.3 records exactly
     that mistake being made and caught).
  3. If and only if you find a real error, fix it and commit with a message saying what
     was wrong. If you find nothing, say so plainly and stop. "I checked and it holds" is
     a complete and correct answer -- do not manufacture work to look busy.

Touch nothing outside RESULTS.md. Do not modify src/, do not touch winnow, do not push.
Be concise in chat; substance goes in RESULTS.md.
EOF
)

timeout 10800 claude -p "$PROMPT" --dangerously-skip-permissions >> "$LOG" 2>&1
echo "=== wake_4am session ended $(date -Is) rc=$?" >> "$LOG"
